export default [
  'Jakie było poprzednie miejsce, gdzie mieszkałeś? Jakie są największe różnice pomiędzy tym, gdzie teraz mieszkasz?',
  'Twoje hobby, o którym nie wszyscy wiedzą',
  'Twój talent, o którym nie wszyscy wiedzą',
  'Opowiedz o jakiejś dziwnej sytuacji, która przydarzyła ci się w życiu',
  'Opowiedz o sytuacji w życiu kiedy byłeś z siebie naprawdę dumny',
  'Opowiedz o sytuacji, która w jakiś sposób, na danym etapie życia, była punktem zwrotnym w twoim życiu',
  'Opowiedz o jakiejś dobrej radzie, którą w życiu dostałeś. Od kogo?',
  'Opowiedz o jednym z czynników, które według Ciebie miały wpływ na twoje wychowanie / na to kim jesteś dzisiaj',
  'Gdybyś z płonącego domu/mieszkania mógł zabrać tylko jedną rzecz, co by to było?',
  'Co włożyłbyś do kapsuły czasu 15 lat temu?',
  'Jaki jest najdziwniejszy komplement, który w życiu dostałeś?',
  'Czy miałeś kiedyś pomysł na biznes/wynalazek, a później okazało się, że ktoś już to wynalazł wcześniej?',
  'Jeśli miałbyś prowadzić jakiś kurs bądź uczyć czegoś w szkole, co by to było?',
  'Jaką super moc chciałbyś mieć?',
  'Jak dla ciebie wygląda idealny weekend?',
  'Jak dla ciebie wygląda idealny urlop?',
  'Do jakiego zwierzaka jesteś podobny?',
  '',
  '',
  '',
  '',
];
