export default [
    'Opowiedz o projekcie w którym najdłużej pracowałeś',
    'Jakie 3 imprezy/wydarzenia/spotkania towarzyskie wyjątkowo wryły Ci się w pamięć i lubisz je wspominać i o nich opowiadać?',
    'Co byś chciał/chciała zrobić, a czego Ci nie wolno?',
    'Kim chcesz być kiedy dorośniesz?',
    'Co myślisz o instytucji małżeństwa?',
    'Jakie samoograniczające przekonania chciałbyś wreszcie pokonać?',
    'Jak się zachowujesz wobec obcych Ci ludzi, którzy do Ciebie zagadują? Jakie historie są z tym związane?',
    'Jaka jest najbardziej nietypowa rzecz, jaką posiadasz?',
    'Jakie są  3 oczekiwania jakie stawiasz samej/samemu sobie?',
    'Opowiedz o ostatnim zakładzie jaki wygrałeś?',
    'Jakie supermoce chciałbyś mieć?',
    'W co byś zainwestował gdybyś miał wolne środki?',
    'Co byś zrobił gdyby kompletnie nie obchodziło Cię zdanie innych ludzi?',
    'Jaka jest najdziwniejsza rzecz, jaką zachowałeś (choć można ją było wyrzucić)?',
    'Na jakie kursy lubisz chodzić?',
    'Jakie są najbardziej pozytywne zmiany, jakie dostrzegasz u siebie na przestrzeni lat?',
    'Na co czujesz się już za stary? Na co jeszcze za młody?',
    'Co robisz, gdy rozmawiasz z kimś reprezentującym kompletnie odmienne od Twoich poglądy?',
    'Opowiedz o zajęciach (szkolnych/rozwojowych) które utkwiły Ci w pamięci/ Dlaczego tak się stało?',
    'Uwielbiam gdy ludzie pytają mnie o …?',
    'Jaką książkę pamiętasz, że czytałeś/aś po raz pierwszy tylko dla przyjemności?',
    'Jakie są Twoje ulubione codzienne, “małe szczęścia” (rytuały)?',
    'Z jakich swoich zachowań jesteś dumny?',
    'W jakim czasie w ciągu dnia czujesz się najbardziej kreatywny? W jaki sposób to wykorzystujesz?',
    'Jakiej rzeczy chciałbyś się nauczyć ot tak, jak za dotknięciem czarodziejskiej różdżki?',
    'Od czego jesteś uzależniony? Czemu akurat od tego?',
    'Do czego masz smykałkę? Jak to realizujesz?',
    'Jakie rzeczy z gatunku nieracjonalnych nadal robisz?',
    'Co jesz zazwyczaj na śniadanie?',
    'Jak postrzegasz porażkę? Wymień istotne dla Ciebie porażki, jakie poniosłeś?',
    'W jaki sposób ćwiczysz?',
    'Opowiedz o najbardziej szalonej rzeczy, jaką kiedykolwiek zrobiłeś',
    'Co jest Ci obojętne?',
    'Opowiedz o najbardziej odważnej rzeczy jaką kiedykolwiek zrobiłeś?',
    'Jakie są Twoje nietypowe umiejętności?',
    'W jakich kwestiach jesteś kreatywny? ',
    'Opowiedz o czymś, co gdybyś zrobił ludzie w Twoim otoczeniu byliby zszokowani, bo jest to tak do Ciebie niepodobne?',
    'Na co Zawsze znajdujesz czas albo zawsze starasz się znajdować?',
    'Jak często zmieniasz pracę? Jakie były najczęstsze powody tych zmian?',
    'Jaką jedną rzecz zabrałbyś z domu, gdyby właśnie się palił?',
    'Co uwielbiasz robić jako dziecko i mogłaś to robić godzinami?',
    'Jak wyglądałeś za czasów nastoletnich? Dlaczego właśnie tak?',
    'Co robisz ze swoimi pomysłami?',
    'Czego nie wiesz o najważniejszej osobie w Twoim życiu?',
    'Co Cię satysfakcjonuje w Twojej pracy?',
    'Jaki masz stosunek do pisania (jako formy twórczej)? Piszesz coś? Pokazujesz to potem komuś czy ląduje w szufladzie? ',
    'Co w sobie najbardziej lubisz: wygląd, osobowość, intelekt? A może jeszcze coś innego? ',
    'Jakiego rodzaju osobą chciałbyś być? ',
    'Co powoduje, że się czerwienisz i zawstydzasz?',
    'A może by tak wszystko rzucić i wyjechać w bieszczady - jakim miejscem byłyby “Twoje bieszczady”? Gdzie byś pojechał? ',
    'Opowiedz zabawną/ciekawą historię związaną ze zwierzętami (Twoimi lub czyimiś)',
    'W co zwykłeś wierzyć przez wiele lat a już - na szczęście! - nie wierzysz? ',
    'Jakie codzienne rutynowe aktywności cenisz sobie o wiele bardziej niż inne?',
    'Z czego jesteś najbardziej dumny?',
    'Kiedy uprawiasz daydreaming, czyli śnienie na jawie - czego dotyczą te marzenia?',
    'Na czym nie lubisz oszczędzać?',
    'Z czego ze swojej przeszłości śmiejesz się teraz od ucha do ucha?',
    'Jakie komplementy często dostajesz? Które z nich najbardziej lubisz?',
    'Jakie są Twoje irytujące zachowania?',
    'Jaka osoba Cię inspiruje i dlaczego? ',
    'W jakie miejsca lubisz chodzić, żeby sobie coś przemyśleć?',
    'Opowiedz o jednej z rozmów telefonicznych, które zmieniły Twoje życie.',
    'Jaki jest Twój największy talent, umiejętność, dar?',
    'Jakiego błędu wychowawczego nie chciałbyś powtórzyć?',
    'Co myślisz o idei Couch Surfingu? Korzystasz?',
    'Wobec kogo (osoba lub grupa społeczna) odczuwasz empatię i rozumiesz ją/ich na jakimś nie namacalnym, wyższym poziomie?',
    'Na jakie organizacje charytatywne dajesz pieniądze i dlaczego?',
    'Jakie dobre, cenne dla Ciebie rady na temat biznesu dostałeś od ludzi?',
    'Czy miałeś kiedykolwiek mentora?',
    'Opowiedz o nim. Jeśli nie , pomyśl kto z Twojego otoczenia w pewien sposób w nim jest.',
    'Czego się bałeś jako dziecko w byciu dorosłym?',
    'Jakie rzeczy wystawiasz trochę na pokaz kiedy przychodzą do Ciebie goście?',
    'Jaką pamiętasz historię na swój temat, którą opowiadasz ludziom umieszczając siebie jako głównego bohatera ale nie wyjawiasz, że nim jesteś? ',
    'Jaki sen miałeś w swoim życiu więcej niż raz?',
    'Jakie rzeczy sprawdzasz lub robisz przed pójściem spać?',
    'Kiedy nie możesz spać, co robisz, by jednak zasnąć?',
    'Jakie dźwięki Ci przeszkadzają?',
    'Co lubisz najbardziej w swoim domu/mieszkaniu?',
    'Jakie dźwięki lubisz?',
    'Jakie są Twoje ulubione miejsca w Polsce',
    'Jakie są Twoje ulubione miejsca w Europie?',
    'Na co nigdy nie znajdujesz czasu choć bardzo byś chciał?',
    'Jakie są Twoje weekendowe rytuały?',
    'Opowiedz o ważnym dla Ciebie nauczycielu. Dlaczego jest dla Ciebie ważny?',
    'Co lubisz czytać i dlaczego?',
    'Jakie są według Ciebie najpiękniejsze słowa w języku polskim?',
    'Jakie nawyki nabyłeś dzięki ludziom wokół Ciebie?',
    'Jakie są Twoje 3 filmy wszechczasów które każdy po prostu “musi” obejrzeć?',
    'Jakie Twoje umiejętności albo talenty są w tej chwili na marnym poziomie przez zaniedbanie lub zaniechanie?',
    'Gdybyś miał odsiadkę w więzieniu, co zrobiłbyś ze swoim czasem?',
    'O czym marzyłeś będąc dzieckiem?',
    'Co chcesz jeszcze w życiu odkryć?',
    'Jakie 3 pytania zadałbyś swoim dzieciom, żeby mogły unikać błędów, które Ty popełniłeś?',
    'W jakich kwestiach możesz pójść na kompromis, a w jakich stanowczo nie?',
    'Opowiedz o najgłupszej rzeczy, jaką kiedykolwiek zrobiłeś',
    'Jacy są ludzie wokół Ciebie - częściej optymistyczni, czy pesymistyczni? A Ty?',
    'Czego nauczyłeś się od swoich wrogów?',
    'Komu pomogłeś w rzuceniu nałogu nawyku lub destrukcyjnego zachowania?',
    'Jakie jest Twoje najczęstsze życzenie, kiedy spada gwiazda, albo kiedy zdmuchujesz świeczkę na urodzinowym torcie?',
    'Gdybyś miał otworzyć restaurację, co byłoby jej specjalnością? ',
    'Jaka by była?',
    'Jakie masz oczekiwania wobec noszonej przez siebie bielizny?',
    'Jaka była Twoja pierwsza praca? Co było w niej fajnego (albo nie)?'    
];